{"ERROR_MESSAGE": "Traceback (most recent call last):\n  File \"F:\\projects\\pythonProjects\\coppellia_project_1\\src\\execution_scripts\\iterator.py\", line 73, in startMainIteration\n    self.analyser.onIteration()\n  File \"F:\\projects\\pythonProjects\\coppellia_project_1\\src\\ananlysing_scripts\\analyser.py\", line 70, in onIteration\n    raise Exception(\"WTF Lol\", \"AHAHHAHA, exception\")\nException: ('WTF Lol', 'AHAHHAHA, exception')\n", "IS_IN_MAIN": true, "CURRENT_DIRECTION": 0.0, "CURRENT_ID": -1, "CURRENT_ANGLE": 37.028785438919755, "READ_IDS": [], "STATE": "MOVING2TARGET"}